### ISSUE TITLE
SIGN like Gconv

### ISSUE THREAD

**Issue by tongnie** [chr26195/PMLP#1]
Hi! Thanks for providing such an insightful paper! These findings in your paper enlighten me a lot and I'd like to go further on this topic. Since SGC is not expressive enough,  I'm curious about how to implement SIGN convolution based on PMLP? Could PMLP works well for multi-hop convolutions? SIGN contains a CONCAT operation, which makes different shapes with/without MP. So how to adapt for this case?

Thanks in advance for your help!

**Comment by chr26195** [comment]
Thanks for reaching out. In terms of implementation, the key idea of PMLP is to ***simply remove all message passing modules of GNNs in training*** while leaving all other parts unchanged. Specifically for SIGN ("SIGN: Scalable Inception Graph Neural Networks"), one can try removing all A matrices in their equation (4) during training and adding them back in inference, which could be implemented with a few lines of codes following our provided examples (where "use_conv=True/False" parameter is used).  

Hope this could help.

**Comment by tongnie** [comment]
Thanks for your quick reply, I'll try it!
