### ISSUE TITLE
Other tasks for PMLP

### ISSUE THREAD

**Issue by tongnie** [chr26195/PMLP#2]
Hi chenxiao, PMLP is domonstrated to be effective for node classification tasks, and I wonder whether PMLP is suitable for node regression tasks (e.g., given a set of node features to predict a set of numeric label values)? 

I'll appreciate for your reply!

**Comment by chr26195** [comment]
Thank you for your continued interest. The main focus of our paper is on inductive node classification, and we have presented results on sixteen datasets. Although we have not tested the performance of PMLP on node regression tasks, we encourage you to explore its potential in such tasks. Feel free to try it out and see how it performs. : )

**Comment by tongnie** [comment]
Thanks for your kind suggestions!
